prometheus:
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [prometheus-server.monitoring.svc.cluster.local:9090]
          
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
          
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.monitoring.svc.cluster.local:8080']

      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['redis-exporter.default.svc.cluster.local:9121']
    

      
